name: 'CI'
on:
  pull_request:
    paths-ignore: [ '**.md' ]
  push:
    paths-ignore: [ '**.md' ]
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test:
    name: Build & Test
    runs-on: [cloud, linux]
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x

      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint
      - run: npm test

      - name: Publish Test Results
        uses: ./
        if: always() && github.event_name != 'pull_request'
        with:
          name: Same-Job Test Results
          path: __tests__/__results__/*.xml
          reporter: jest-junit

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: __tests__/__results__/*.xml
          retention-days: 1

      - name: Upload Action
        if: always() && github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: action
          path: |
            action.yml
            dist/index.js
          retention-days: 1

  artifact:
    name: Same-Workflow Artifact Test
    needs: build-test
    if: always() && github.event_name != 'pull_request'
    runs-on: [cloud, linux]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Publish Test Results
        uses: ./action/
        with:
          name: Same-Workflow Test Results
          path: 'test-results/*.xml'
          reporter: jest-junit
