name: 'CI'
on:
  pull_request:
    paths-ignore: [ '**.md' ]
  push:
    paths-ignore: [ '**.md' ]
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test:
    name: Build & Test
    runs-on: [cloud, linux]
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x

      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint
      - run: npm test

      - name: Inline Test
        uses: ./
        if: always()
        with:
          name: Inline
          path: __tests__/__results__/*.xml
          reporter: jest-junit

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: __tests__/__results__/*.xml

      - name: Cache Test Results
        uses: actions/cache@v3
        with:
          path: |
            action.yml
            dist/index.js
            __tests__/__results__/*.xml
          key: ${{ github.sha }}-test-results

  artifact:
    name: Same-Workflow Artifact Test
    needs: build-test
    runs-on: [cloud, linux]
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        artifact: test-results
        name: Same-Workflow Artifact
        path: '*.xml'
        reporter: jest-junit

  cache:
    name: Cache Test
    needs: build-test
    runs-on: [cloud, linux]
    steps:
      - name: Restore Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            action.yml
            dist/index.js
            __tests__/__results__/*.xml
          key: ${{ github.sha }}-test-results

      - name: Inline Test
        uses: ./
        with:
          name: Cache
          path: __tests__/__results__/*.xml
          reporter: jest-junit
