name: Workflow-Run Arifact Test

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  artifact:
    name: Workflow-Run Arifact Test
    runs-on: [cloud, linux]
    steps:
    - uses: actions/checkout@v3

    - name: Publish Test Results
      uses: ./
      with:
        artifact: test-results
        name: Workflow-Run Test Results
        path: '*.xml'
        reporter: jest-junit
